---
swagger: '2.0'

info:
  version: '0.1'
  title: Gamie
  description: a test bed for swagger hapi api generation

schemes:
  - http
  - https

paths:
  /game:
    get:
      responses:
        200:
          description: retrieves game data
          schema:
            title: Game
            type: object
            required:
              - name
              - players
            properties:
              id:
                type: integer
                example: 14606
              name:
                type: string
                example: Exploding Kittens
              players:
                type: integer
                example: 5
              type:
                type: string
                example: Card
      produces:
        - application/json
  /games:
    get:
      responses:
        200:
          description: retrieves game data
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
      produces:
        - application/json
    post:
      parameters:
        - name: Game
          in: body
          description: Game payload
          required: true
          schema:
            title: GamePayload
            type: object
            required:
              - name
              - type
            properties:
              name:
                type: string
                example: fancy game
              players:
                type: integer
                example: 5
              type:
                enum:
                  - Card
                  - Minitues
                example: Card
      responses:
        200:
          description: retrieves game data
          schema:
            $ref: '#/definitions/Game'
      produces:
        - application/json

  /games/{gameId}:
    get:
      parameters:
      - name: gameId
        in: path
        description: ID of the Game to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: retrieves game data
          schema:
            $ref: '#/definitions/Game'
      produces:
        - application/json
    put:
      parameters:
      - name: gameId
        in: path
        description: ID of the Game to update
        required: true
        type: integer
        format: int64
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/Game'
      responses:
        200:
          description: retrieves game data
          schema:
            $ref: '#/definitions/Game'
      produces:
        - application/json
    delete:
      parameters:
      - name: gameId
        in: path
        description: ID of the Game to delete
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: retrieves game data
          schema:
            $ref: '#/definitions/Game'
      produces:
        - application/json

definitions:
  GameLight:
    type: object
    properties:
      name:
        type: string
        example: Exploding Kittens
      players:
        type: integer
        format: int64
        example: 5
      type:
        type: string
        example: Card
  Game:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 14606
      name:
        type: string
        example: Exploding Kittens
      players:
        type: integer
        format: int64
        example: 5
      type:
        type: string
        example: Card
        enum:
        - Card
        - Minitue
    xml:
      name: Game
